# Generated by Django 4.2.4 on 2023-08-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Militar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grado", models.CharField(max_length=150)),
                ("nombre", models.CharField(max_length=150)),
                ("matricula", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("motivo", models.TextField()),
                ("hora_llegada", models.TimeField()),
                ("hora_salida", models.TimeField()),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ausencias.militar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("inicio", models.DateField()),
                ("termino", models.DateField()),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ausencias.militar",
                    ),
                ),
            ],
        ),
    ]
